name: Coverage

on: [push]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Dependencies
        run: yarn
      - name: Update Modules
        run: yarn sync
      - name: Run Coverage
        run: FOUNDRY_PROFILE=ci yarn coverage